import { Type } from 'class-transformer';
import {
  IsBoolean,
  IsIn,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  Min,
} from 'class-validator';

export class CreateSaleworkDebtDto {
  @IsInt()
  @Min(1)
  merchantId!: number;

  @IsNumber()
  @Min(0)
  amount!: number;

  @IsString()
  @IsNotEmpty()
  billRef!: string;

  @IsString()
  @IsNotEmpty()
  payer!: string;

  @IsOptional()
  @IsString()
  note?: string;

  @IsOptional()
  @IsIn(['ACTIVE', 'COLLECTED', 'CANCELLED'])
  status?: 'ACTIVE' | 'COLLECTED' | 'CANCELLED';

  @IsOptional()
  @IsString()
  userInCharge?: string;

  @IsOptional()
  @IsBoolean()
  isBillRefAutoGenerated?: boolean;
}

export class GenerateSaleworkQrDto {
  @Type(() => Number)
  @IsInt()
  @Min(1)
  merchantId!: number;

  @IsString()
  @IsNotEmpty()
  billRef!: string;
}
